'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''

def main():
    first = 1
    second = 2
    sum = 0
    sum = fib_rec(first, second, sum)
    print(sum)

def fib_rec(prev1, prev2, sum):
    sum = sum if prev1%2 else sum + prev1
    if prev2 > 4000000:
        return sum
    else:
        return fib_rec(prev2, prev1+prev2, sum)

if __name__ == '__main__':
    main()